/** Generated by scripts/fetch-fonts.mjs — do not edit. */

import font0 from "../assets/fonts/dm-sans-latin.ca72d2bc.woff2?url";
import font1 from "../assets/fonts/space-grotesk-latin.06408904.woff2?url";

/**
 * The faces the first screen needs, preloaded by the root route.
 *
 * Real imports, so the URLs are whatever Vite emitted — a regenerated font
 * cannot leave a preload pointing at a name that no longer exists, and a
 * missing file is a build error rather than a 404 nobody notices.
 */
export const PRELOAD_FONTS = [font0, font1];
