/**
 * Downloads the webfonts into `public/fonts` and regenerates `src/fonts.css`.
 *
 * Run it after changing a weight in FAMILIES; it is not part of the build, so
 * the files it writes are committed. Only latin and latin-ext are kept — the
 * Google build also ships Vietnamese, Greek and Cyrillic, none of which this
 * site can render a word of.
 *
 *   node scripts/fetch-fonts.mjs
 *
 * The files land in `src/assets/fonts` rather than `public/`, so Vite fingerprints
 * and emits them like any other asset. That is what gets them a year of
 * `immutable`: nitro serves `public/` from a handler that sits in front of the
 * app, so headers set in `server.ts` never reach anything under it, while
 * everything Vite emits into `/assets` is already cached that way.
 *
 * Writing one file per distinct payload collapses the duplicates. All three families are
 * variable fonts: Google serves one file per subset covering the whole weight
 * range and hands back the same bytes for each weight asked for. Under the old
 * per-weight names that was sixteen files and five downloads on a first visit,
 * two of them byte-identical to another — about 85 KB of the same fonts twice.
 * Six payloads, three of them ever fetched, is the whole set.
 *
 * The two faces above the fold are written to `src/lib/fonts.ts` for the root
 * route to preload, so those URLs cannot drift out of step with these files.
 */
import { createHash } from "node:crypto";
import { mkdir, readdir, unlink, writeFile } from "node:fs/promises";

const FAMILIES = [
  "Space+Grotesk:wght@400;500;600;700",
  "DM+Sans:opsz,wght@9..40,400;9..40,500",
  "JetBrains+Mono:wght@400;500",
];
const KEEP = new Set(["latin", "latin-ext"]);
// Google serves woff2 only to a browser it recognises; with node's UA it
// answers with truetype, which is roughly twice the size.
const UA =
  "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36";

const url = `https://fonts.googleapis.com/css2?${FAMILIES.map((f) => `family=${f}`).join("&")}&display=swap`;
const css = await fetch(url, { headers: { "User-Agent": UA } }).then((r) => r.text());

const dir = new URL("../src/assets/fonts/", import.meta.url);
await mkdir(dir, { recursive: true });

// Everything currently there is about to be replaced by a differently-named
// copy of itself; leaving the old names behind would ship both.
for (const stale of await readdir(dir)) {
  if (stale.endsWith(".woff2")) await unlink(new URL(stale, dir));
}

/** The faces the hero needs before anything else can be read. */
const PRELOAD = new Set(["DM Sans 400 latin", "Space Grotesk 600 latin"]);

const faces = [];
const preload = [];
const written = new Set();
let bytes = 0;
for (const [, subset, block] of css.matchAll(
  /\/\*\s*([a-z0-9-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g,
)) {
  if (!KEEP.has(subset)) continue;
  const at = (re) => block.match(re)?.[1].trim();
  const family = at(/font-family:\s*'([^']+)'/);
  const weight = at(/font-weight:\s*([^;]+);/);
  const style = at(/font-style:\s*([^;]+);/);
  const range = at(/unicode-range:\s*([^;]+);/);
  const href = at(/url\(([^)]+)\)/);

  const data = new Uint8Array(await fetch(href).then((r) => r.arrayBuffer()));
  const hash = createHash("sha256").update(data).digest("hex").slice(0, 8);
  // Vite adds its own hash to the emitted name; this one only has to keep two
  // different payloads from claiming the same source filename.
  const name = `${family.toLowerCase().replace(/ /g, "-")}-${subset}.${hash}.woff2`;

  // Two weights of a variable font are the same bytes; write it once and let
  // both @font-face rules point at the one file.
  if (!written.has(name)) {
    written.add(name);
    await writeFile(new URL(name, dir), data);
    bytes += data.byteLength;
  }
  if (PRELOAD.has(`${family} ${weight} ${subset}`)) preload.push(name);

  faces.push(`/* ${family} ${weight} — ${subset} */
@font-face {
  font-family: "${family}";
  font-style: ${style};
  font-weight: ${weight};
  font-display: swap;
  src: url("./assets/fonts/${name}") format("woff2");
  unicode-range: ${range};
}`);
}

await writeFile(
  new URL("../src/fonts.css", import.meta.url),
  `/*
 * Self-hosted webfonts — generated by scripts/fetch-fonts.mjs, do not edit.
 *
 * These used to come from fonts.googleapis.com, which put a render-blocking
 * stylesheet and two extra DNS + TLS handshakes on the critical path, and told
 * a third party about every visitor. From the site's own origin they need
 * neither, and unicode-range still means a browser only pulls the subsets it
 * has characters for.
 */

${faces.join("\n\n")}
`,
);
await writeFile(
  new URL("../src/lib/fonts.ts", import.meta.url),
  `/** Generated by scripts/fetch-fonts.mjs — do not edit. */

${preload.map((n, i) => `import font${i} from "../assets/fonts/${n}?url";`).join("\n")}

/**
 * The faces the first screen needs, preloaded by the root route.
 *
 * Real imports, so the URLs are whatever Vite emitted — a regenerated font
 * cannot leave a preload pointing at a name that no longer exists, and a
 * missing file is a build error rather than a 404 nobody notices.
 */
export const PRELOAD_FONTS = [${preload.map((_, i) => `font${i}`).join(", ")}];
`,
);

console.log(
  `${faces.length} faces over ${written.size} files, ${Math.round(bytes / 1024)} KB, ${preload.length} preloaded`,
);
