/**
 * Downloads the webfonts into `public/fonts` and regenerates `src/fonts.css`.
 *
 * Run it after changing a weight in FAMILIES; it is not part of the build, so
 * the files it writes are committed. Only latin and latin-ext are kept — the
 * Google build also ships Vietnamese, Greek and Cyrillic, none of which this
 * site can render a word of.
 *
 *   node scripts/fetch-fonts.mjs
 */
import { mkdir, writeFile } from "node:fs/promises";

const FAMILIES = [
  "Space+Grotesk:wght@400;500;600;700",
  "DM+Sans:opsz,wght@9..40,400;9..40,500",
  "JetBrains+Mono:wght@400;500",
];
const KEEP = new Set(["latin", "latin-ext"]);
// Google serves woff2 only to a browser it recognises; with node's UA it
// answers with truetype, which is roughly twice the size.
const UA =
  "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36";

const url = `https://fonts.googleapis.com/css2?${FAMILIES.map((f) => `family=${f}`).join("&")}&display=swap`;
const css = await fetch(url, { headers: { "User-Agent": UA } }).then((r) => r.text());

const dir = new URL("../public/fonts/", import.meta.url);
await mkdir(dir, { recursive: true });

const faces = [];
let bytes = 0;
for (const [, subset, block] of css.matchAll(
  /\/\*\s*([a-z0-9-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g,
)) {
  if (!KEEP.has(subset)) continue;
  const at = (re) => block.match(re)?.[1].trim();
  const family = at(/font-family:\s*'([^']+)'/);
  const weight = at(/font-weight:\s*([^;]+);/);
  const style = at(/font-style:\s*([^;]+);/);
  const range = at(/unicode-range:\s*([^;]+);/);
  const href = at(/url\(([^)]+)\)/);

  const name = `${family.toLowerCase().replace(/ /g, "-")}-${weight.replace(/ /g, "-")}-${subset}.woff2`;
  const data = new Uint8Array(await fetch(href).then((r) => r.arrayBuffer()));
  await writeFile(new URL(name, dir), data);
  bytes += data.byteLength;

  faces.push(`/* ${family} ${weight} — ${subset} */
@font-face {
  font-family: "${family}";
  font-style: ${style};
  font-weight: ${weight};
  font-display: swap;
  src: url("/fonts/${name}") format("woff2");
  unicode-range: ${range};
}`);
}

await writeFile(
  new URL("../src/fonts.css", import.meta.url),
  `/*
 * Self-hosted webfonts — generated by scripts/fetch-fonts.mjs, do not edit.
 *
 * These used to come from fonts.googleapis.com, which put a render-blocking
 * stylesheet and two extra DNS + TLS handshakes on the critical path, and told
 * a third party about every visitor. From the site's own origin they need
 * neither, and unicode-range still means a browser only pulls the subsets it
 * has characters for.
 */

${faces.join("\n\n")}
`,
);
console.log(`${faces.length} faces, ${Math.round(bytes / 1024)} KB`);
